<script lang="ts">
	import { base } from '$app/paths';

	const title = 'FAQ';

	import animatedDetails from '$lib/animation/animatedDetails';
	import Glos from '$lib/assets/media/glos4-tamniji-4-min.png';
	import Telegram from '$lib/assets/media/telegram.svg';
	import SvelteMarkdown from 'svelte-markdown';

	const faqs = [
		{
			title: 'What is DeepSquare?',
			content: `Deep**Square** is a decentralised sustainable cloud ecosystem focused on High-Performance
Computing using blockchain technology to provide world-class performance and transparency.
DeepSquare delivers a decentralised High-Performance Computing as a Service (HPCaaS) platform
that aims to make HPC resources more accessible and cost-effective for individuals and organisations
of all sizes.`
		},
		{
			title: 'What is HPC?',
			content: `**High-Performance Computing (HPC)** is the use of powerful computing systems to perform complex and data-intensive calculations, simulations, and analyses. HPC systems are used in a wide range of applications, including scientific research, engineering, weather forecasting, and financial modelling.`
		},
		{
			title: 'What is cloud computing for?',
			content: `Cloud computing is the delivery of computing services, including servers, storage, databases, networking, software, analytics, and intelligence using the cloud to offer faster innovation, flexible resources, and economies of scale.`
		},
		{
			title: 'What is DeepSquare Platform',
			content: `The DeepSquare platform serves as a gateway for users to access and manage HPC resources through a decentralised network of supercomputers: the  DeepSquare Federated Grid. It consists of various components that work together to provide users with an efficient and powerful computing experience. `
		},
		{
			title: 'What is Mondriant Testnet',
			content: `[The Mondrian subnet](https://testnet.avascan.info/blockchain/mondrian/info) provides a fully functional HPC environment for developers to test and deploy their applications for free. This alternative to the free credits locking mechanism offered by current cloud providers allows developers to experiment with computationally intensive workloads, streamlining their development process.`
		},
		{
			title: 'Why is DeepSquare environmentally friendly?',
			content: `Power efficiency is essential to reducing greenhouse gas (GHG) emissions and minimising the environmental impact of HPC operations. DeepSquare employs immersion cooling technology to cool its equipment, reducing the electricity needed for cooling by over 25 times compared to traditional air-cooled data centres. The system recovers up to 94% of the heat generated by computing operations, making it highly efficient. DeepSquare also employs a circular economy approach, where it recovers and sells the heat generated by computing operations, creating a valuable co-product.`
		},
		{
			title: 'Where can I buy DPS?',
			content: `We are currently in the private sale stage. For more info, please check the [Investors](${base}/investors) page or reach out to the team.`
		}
	];
</script>

<svelte:head>
	<title>{title} - DeepSquare</title>
	<meta
		name="description"
		content="Find answers to common questions about DeepSquare and its products and services."
	/>
</svelte:head>

<section id="faqs" class="m-0">
	<header>
		<h1>{title}</h1>

		<p>
			DeepSquare's FAQ offers comprehensive answers to common inquiries users may have about various
			aspects of DeepSquare.
		</p>
	</header>

	<main>
		{#each faqs as { title, content }}
			<details use:animatedDetails={{ duration: 200 }}>
				<summary>{title}</summary>

				<SvelteMarkdown source={content} />
			</details>
		{/each}
	</main>
</section>

<section class="py-4 relative mini-section">
	<div
		class="absolute inset-0"
		style="background-image: url(&quot;{Glos}&quot;); background-position: center center; background-repeat: no-repeat; background-size: contain;"
	></div>
	<center>
		<h4>Join our Community</h4>
		<div>
			<a href="https://t.me/DeepSquareProject" target="_blank">
				<img style="filter: var(--mono-img-filter);" id="telegram" src={Telegram} alt="Telegram" />
			</a>
		</div>
	</center>
</section>
